package org.Scsp.com.Enum;


public enum CustomLogicKey {
    MONEY_SAVED_100K,
    MONEY_SAVED_500K,
    MONEY_SAVED_1M,
    MONEY_SAVED_5M,

    DAYS_QUIT_SMOKING_14,
    DAYS_QUIT_SMOKING_30,

    STREAK_NO_SMOKE_1,
    STREAK_NO_SMOKE_7,
    STREAK_NO_SMOKE_30,

    FIRST_DAY,

    NUMBER_OF_DIARY_1,
    NUMBER_OF_DIARY_7,
    NUMBER_OF_DIARY_30,

    NUMBER_OF_TASK_COMPLETE_5,
    NUMBER_OF_TASK_COMPLETE_10,
    NUMBER_OF_TASK_COMPLETE_20,
    NUMBER_OF_TASK_COMPLETE_30,
    NUMBER_OF_TASK_COMPLETE_50,
    NUMBER_OF_TASK_COMPLETE_100,

    HEALTHY_MILESTONE_20_MIN,
    HEALTHY_MILESTONE_8_HOURS,
    HEALTHY_MILESTONE_12_HOURS,
    HEALTHY_MILESTONE_1_DAY,
    HEALTHY_MILESTONE_2_DAYS,
    HEALTHY_MILESTONE_3_DAYS,
    HEALTHY_MILESTONE_14_DAYS,
    HEALTHY_MILESTONE_30_DAYS,
    HEALTHY_MILESTONE_90_DAYS,
    HEALTHY_MILESTONE_180_DAYS,
    HEALTHY_MILESTONE_1_YEAR,
    HEALTHY_MILESTONE_5_YEARS,
    HEALTHY_MILESTONE_10_YEARS,
    HEALTHY_MILESTONE_15_YEARS,
}
